# application-example.yml
# application-test.yml, application-dev.yml 는 뭐 실수로 올려도 되나 application-prod.yml는 올리지마세요.

spring:
  config:
    activate:
      on-profile: example  # example 프로필이 활성화되었을 때만 적용됨

  datasource:
    url: jdbc:mysql://localhost:3306/emr  # 프로덕션용 데이터베이스 URL
    username: root  # 프로덕션용 데이터베이스 사용자명
    password: 1234  # 프로덕션용 데이터베이스 비밀번호